Repository mcdope/pam_usb, pull requests merged in 2025-03, with the labels that each got.

#266 add check for VSCode remote tunnel
  src/local.c
Labels: enhancement, security

#267 CI: Fix image handling
  .github/workflows/build-and-test-on-own-server.yml
  .github/workflows/nightly-build-on-own-server.yml
  .github/workflows/package-with-docker-on-own-server.yml
  src/volume.c
  tests/can-actually-be-used/mount-image.sh
Labels: bug

#268 Add CONTRIBUTING
  CONTRIBUTING
Labels: documentation
